### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by miparnisari** [mrmrs/pesticide#49]
```javascript
pesticide.js:3 Uncaught TypeError: Cannot set property 'innerHTML' of null
    at init (chrome-extension://bblbgcheenepgnnajgfpiicnbbdmmooh/pesticide.js:3:26)
    at chrome-extension://bblbgcheenepgnnajgfpiicnbbdmmooh/pesticide.js:32:1
```

I don't have any repro steps unfortunately :(

**Comment by mrmrs** [comment]
@miparnisari First off - sorry you had an error! Secondly - do you know what page you tried to use it on?

**Comment by miparnisari** [comment]
I was debugging an app of mine. I don't know what I did, it just appeared.
